version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "tmgcat-pgdb"
      POSTGRES_USER: "tmgcat-pguser"
      POSTGRES_PASSWORD: "pgpwd4tmgc"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - tmgcatdb-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tmgcat-pguser -d tmgcat-pgdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres


volumes:
  tmgcatdb-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge